# Generated by Django 4.0.3 on 2022-04-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('beds', models.IntegerField()),
                ('price', models.IntegerField()),
                ('room_pic', models.ImageField(upload_to='profile_pics')),
            ],
        ),
    ]
