# Generated by Django 4.0.3 on 2022-04-19 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_booked_on_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 15, 44, 15, 224096, tzinfo=utc)),
        ),
    ]
