# Generated by Django 4.0.3 on 2022-04-23 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_booked_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stay',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 6, 53, 36, 997848, tzinfo=utc)),
        ),
    ]
