# Generated by Django 4.0.3 on 2022-04-23 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_stay_alter_booking_booked_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 16, 18, 1, 368086, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='ac',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'No')], default='Available', max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='wifi',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'No')], default='Available', max_length=15),
        ),
    ]
